name: Build, Test and Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.204

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: |
        cd Fluent.CodeGen
        dotnet build --configuration Release --no-restore

    - name: Test
      run: |
        dotnet test 

    - name: Pack
      run: |  
        cd Fluent.CodeGen
        dotnet pack -c Release -o out

    - name: Publish Fluent.CodeGen to nuget.org
      run: |
        dotnet nuget push ./Fluent.CodeGen/out/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate